#!/usr/bin/env python3
"""Generate the small C++ registry and binary-object plan for embedded HSACO."""

# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Approaching AI Authors

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def binary_symbol(filename: str) -> str:
    return "_binary_" + re.sub(r"[^A-Za-z0-9_]", "_", filename)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", action="append", type=Path, required=True)
    parser.add_argument("--output-cpp", type=Path, required=True)
    parser.add_argument("--output-plan", type=Path, required=True)
    args = parser.parse_args()
    selected: dict[str, tuple[dict[str, object], Path]] = {}
    for source in args.manifest:
        manifest_path = source.resolve()
        root = manifest_path.parent
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        if manifest.get("schema") != "aima-amd395-qwen36/native-aot-closure/v1":
            raise SystemExit(f"unsupported native AOT manifest: {manifest_path}")
        kernels = manifest.get("kernels")
        if not isinstance(kernels, list) or len(kernels) != manifest.get("kernel_count"):
            raise SystemExit(f"native AOT manifest kernel count mismatch: {manifest_path}")
        for kernel in kernels:
            kernel_hash = str(kernel["kernel_hash"])
            previous = selected.get(kernel_hash)
            if previous is not None:
                previous_kernel, previous_root = previous
                previous_image = previous_kernel["image"]
                image = kernel["image"]
                if (
                    previous_kernel["symbol"] != kernel["symbol"]
                    or previous_kernel["metadata"] != kernel["metadata"]
                    or previous_image["sha256"] != image["sha256"]
                    or previous_image["bytes"] != image["bytes"]
                ):
                    raise SystemExit(
                        "native AOT kernel hash has conflicting manifests: "
                        f"{kernel_hash} ({previous_root}, {root})"
                    )
                continue
            selected[kernel_hash] = (kernel, root)

    declarations: list[str] = []
    entries: list[str] = []
    plan: list[str] = []
    for index, kernel_hash in enumerate(sorted(selected)):
        kernel, root = selected[kernel_hash]
        image = kernel["image"]
        image_path = (root / image["path"]).resolve()
        if not image_path.is_file() or image_path.stat().st_size != image["bytes"]:
            raise SystemExit(f"native AOT image size mismatch: {image_path}")
        if sha256_file(image_path) != image["sha256"]:
            raise SystemExit(f"native AOT image hash mismatch: {image_path}")
        filename = image_path.name
        symbol = binary_symbol(filename)
        declarations.append(f"extern const unsigned char {symbol}_start[];")
        metadata = kernel["metadata"]
        entries.append(
            "  {\"%s\", \"%s\", %s_start, %d, %d, %d, %d},"
            % (
                kernel["kernel_hash"],
                kernel["symbol"],
                symbol,
                image["bytes"],
                metadata["num_warps"],
                metadata["warp_size"],
                metadata["shared"],
            )
        )
        plan.append(f"{image_path}\t{index:03d}-{filename}.o\t{filename}")

    cpp = """// Generated by scripts/generate-native-aot-registry.py. Do not edit.
// SPDX-License-Identifier: Apache-2.0

#include "aima/aot_registry.h"

#include <cstring>

extern "C" {
%s
}

namespace aima {
namespace {
const EmbeddedAotImage kImages[] = {
%s
};
}  // namespace

const EmbeddedAotImage* embedded_aot_images(std::size_t* count) {
  if (count != nullptr) *count = sizeof(kImages) / sizeof(kImages[0]);
  return kImages;
}

const EmbeddedAotImage* find_embedded_aot_image(const std::string& kernel_hash) {
  for (const auto& image : kImages) {
    if (kernel_hash == image.kernel_hash) return &image;
  }
  return nullptr;
}

}  // namespace aima
""" % ("\n".join(declarations), "\n".join(entries))
    args.output_cpp.parent.mkdir(parents=True, exist_ok=True)
    args.output_plan.parent.mkdir(parents=True, exist_ok=True)
    args.output_cpp.write_text(cpp, encoding="utf-8")
    args.output_plan.write_text("\n".join(plan) + "\n", encoding="utf-8")
    print(
        json.dumps(
            {
                "kernel_count": len(selected),
                "manifest_count": len(args.manifest),
                "output_cpp": str(args.output_cpp),
            }
        )
    )


if __name__ == "__main__":
    main()
